### ISSUE TITLE
Table of Figures

### ISSUE THREAD

**Issue by mmostajab** [fwalch/tum-thesis-latex#10]
My thesis figure captions are too long. So, I have described everything for lazy reader who just look at the figures, there. So, for example the figures looks like this:

![sample](https://cloud.githubusercontent.com/assets/4034259/12217855/47618a2a-b70e-11e5-963d-48743f36f8e8.png)

Can you please tell if you know a way to just use the bold part in the list of figures. I don't like to get a list of figures like this:

![sampple2](https://cloud.githubusercontent.com/assets/4034259/12217879/c17146d4-b70e-11e5-935d-6e563d844a63.png)

Additionally, I wanted to have list of listings for codes. Can you please guide me how can I do that?

Thanks in advanced.

**Comment by fwalch** [comment]
These questions are not really related to the template.. but anyway, the following links should have what you want:

https://en.wikibooks.org/wiki/LaTeX/Floats,_Figures_and_Captions#Lists_of_figures_and_tables
https://en.wikibooks.org/wiki/LaTeX/Source_Code_Listings#Automating_file_inclusion
