### ISSUE TITLE
Logo files not found

### ISSUE THREAD

**Issue by TheHugeManatee** [fwalch/tum-thesis-latex#11]
I had problems typesetting the template on windows with latest MikTex installation (2.9). Although following the Getting Started guide to download the faculty logos, they could not be found by latex. changing the file specification to include file endings fixed the problem:
```latex
  \includegraphics[width=20mm]{logos/faculty.pdf}
```

**Comment by mmostajab** [comment]
Have you downloaded them from TUM website?

**Comment by fwalch** [comment]
Hey! Sorry it took so long to respond.. from what I can tell, that should be supported by MikTeX, not sure what went wrong. I don't have access to a Windows machine to test, so I just changed it in the template.
