### ISSUE TITLE
Logo links are broken

### ISSUE THREAD

**Issue by mohamed-ezz** [fwalch/tum-thesis-latex#14]
The links to the Logo files in README.md are now broken. I'm referring to this part of the README : 

> Download the TUM logo from **here** and save it to logos/tum.pdf.
> Download your faculty's logo from **here** and save it to logos/faculty.pdf.

Unfortunately, I could not find the updated links on https://portal.mytum.de

**Comment by fwalch** [comment]
The logos are currently not available anywhere on the website, as far as I know.. There is some logo section, but accessing it gives a permission error for me.

**Comment by fwalch** [comment]
A friend just told me that he wrote an email and got the response that logos shouldn't be used under the new corporate design. Soo.. I don't know.

**Comment by mohamed-ezz** [comment]
hmmm...ok. 
Meanwhile, I got a vectorized version of the TUM logo from a friend, plus a low-res .png version of the faculty logo. Are we allowed to store these directly on github ? I can create a pull request.

**Comment by fwalch** [comment]
I have the logos (as .pdf) lying around as well, I can send them to you.. I just don't want to store them somewhere myself because it's bound to cause copyright problems :-/

**Comment by mohamed-ezz** [comment]
Yes if you can send them, that'd be helpful : moh.ezz8[at]gmail

**Comment by jpbernius** [comment]
> Sehr geehrte Herr Bernius,
> 
> Sie müssen am Lehrstuhl nach dem Logo fragen. Leider ist es nicht mehr möglich in mytum es runterzuladen. 
> 
> Mit freundlichen Grüßen / Best regards,
> Ihr / Your IT-Support Team

**Comment by sebastian-schlecht** [comment]
Do you guys have the logo of the faculty of electrical and computer engineering lying around as well?

**Comment by mqne** [comment]
There is another TUM template (for dissertations) which links in its README the university and faculty logos:
https://github.com/TUM-LIS/tum-dissertation-latex#link-list-of-logo-resources

**Comment by fwalch** [comment]
Archiving the repo, see readme.
