### ISSUE TITLE
Different footer-height on Sharelatex

### ISSUE THREAD

**Issue by mammuth** [fwalch/tum-thesis-latex#17]
When using this template on Sharelatex, the footer-height is different than the example pdf in the repo and also different when I compile it manually.

Does anyone have a clue how to make the footer smaller on Sharelatex? Or why this happens?

<img width="1637" alt="sharelatex-margin 1" src="https://cloud.githubusercontent.com/assets/3121306/22334106/b5ee41f6-e3d9-11e6-944c-c09113e11f5b.png">

Answer by the Sharelatex support:

> Unfortunately I've been unable to reproduce the problem but I have an idea as to why it might be happening. You may have a different page size set up as the default for your texlive installation than the one on ShareLaTeX i.e. US or letter paper instead of a4. To change the default paper size in TeXlive, you use tlmgr as shown below: 
> tlmgr paper letter
> tlmgr paper a4

**Comment by fwalch** [comment]
As it works when you compile it manually, it seems like the problem is with ShareLaTeX and not with the template. Maybe they have a different version of TeX Live? The template sets the paper size to A4 in `main.tex`.
