### ISSUE TITLE
How to add appendices to the very end of the document

### ISSUE THREAD

**Issue by mshtang** [fwalch/tum-thesis-latex#23]
Hi,

first, thank you very much for sharing this template. I find it very useful to my master thesis typesetting. 

I would like to know how can I add some appendices that dedicate to show some tables at the very end of the document?

I tried to add these lines to the` main.tex`:
```
...
\printbibliography{}
% the above stays unchanged while the following is added in attempt to include some appendices
\appendix
\chapter{An appendix}
\input{pages/appendix.tex}
\chapter{Another appendix}
\input{pages/appendix2.tex}
\end{document}
```
However, the output is not what I was expecting. I would like to have one thing: such entries 
```
A. An Appendix ...................................... xx
B. Another Appendix ...............................  xx
```
in the ToC. 
Second thing: "An Appendix" and "Another Appendix" starts with a new page respectively after the bibliography, just like two new chapters in the main matter. The title on the new pages should be something like "A. An Appendix" and "B. Another Appendix". The tables in "An Appendix" should have numbering A.1, A.2, etc. while tables in "Another Apendix" have B.1, B.2 etc.  And these tables should be listed in the "List of Tables" page.

How do I achieve that? Thank you very much again for your help!

**Comment by fwalch** [comment]
I already get the behavior which you are describing ("A. appendix" in ToC, "B.1 table" in list of tables) by default. I tested with:

```diff
diff --git a/build/main.pdf b/build/main.pdf
index 7b8ce24..4e2c3a7 100644
Binary files a/build/main.pdf and b/build/main.pdf differ
diff --git a/main.tex b/main.tex
index cbb3c85..814cb5e 100644
--- a/main.tex
+++ b/main.tex
@@ -48,5 +48,12 @@
 \listoftables{}
 \microtypesetup{protrusion=true}
 \printbibliography{}
+\chapter{Foo}
+Foo
+\chapter{Bar}
+bar
+\begin{table}
+  \caption{Bar}
+\end{table}
 
 \end{document}
```

See PDF: [main.pdf](https://github.com/fwalch/tum-thesis-latex/files/2793321/main.pdf)

**Comment by fwalch** [comment]
Archiving the repo, see readme.
