### ISSUE TITLE
\subsubsection

### ISSUE THREAD

**Issue by sebo313** [fwalch/tum-thesis-latex#24]
Hi @fwalch,

thank you for providing this great template! 

I am trying to go one level deeper in the indexing, but` \subsubsection` does not work as it is not displayed in the table of contents. Any idea how to solve it?

**Comment by AlexanderLill** [comment]
Hi @sebo313 

have you tried the solution suggested in https://tex.stackexchange.com/questions/17877/how-to-show-subsubsections-and-paragraphs-in-toc ?

**Comment by sebo313** [comment]
Thank @AlexanderLill, it works perfectly!

**Comment by AlexanderLill** [comment]
You're welcome @sebo313 , but I did nothing more than googling for "latex show subsubsection in table of contents" :)
