### ISSUE TITLE
Bibliography formating in the template

### ISSUE THREAD

**Issue by log92** [fwalch/tum-thesis-latex#27]
Dear all,

first of all, thanks for the great template!

I want to adjust my bibliography such that only the initial of the authors' first names are displayed. That would be the library option "giveninits=true". But how can I add this option in the template? I am missing the location where the library package is included (\usepackage[options, options, giveninits=true]{biblatex}). Thank you for your help!

Best,
Lorenz

**Comment by fwalch** [comment]
Archiving the repo, see readme.
