### ISSUE TITLE
Pseudo Code example

### ISSUE THREAD

**Issue by AlexReimann** [fwalch/tum-thesis-latex#5]
A pseudo code example would be nice.

**Comment by fwalch** [comment]
There are a few packages for this, so I'm not sure which one would be best to use.. do you have a suggestion?

**Comment by Phylu** [comment]
For nice code highlighting I always use minted. The packag however needs a python installation, but gives the best results for nice formatted code in my opinion.

**Comment by koppor** [comment]
An installation guide for [pygments](http://pygments.org/) (required by [minted](https://www.ctan.org/pkg/minted)) together with a latex configuration is provided at the "scientific thesis template". See <http://latextemplates.github.io/scientific-thesis-template/> for more information.

**Comment by fwalch** [comment]
Archiving the repo, see readme.
