### ISSUE TITLE
Bibliography issue

### ISSUE THREAD

**Issue by vinodrajendran001** [fwalch/tum-thesis-latex#8]
When I do compile, after adding citations, I am getting the following error.

This is BibTeX, Version 0.99d (TeX Live 2013/Debian)
The top-level auxiliary file: main.aux
I found no \citation commands---while reading file main.aux
I found no \bibdata command---while reading file main.aux
I found no \bibstyle command---while reading file main.aux
(There were 3 error messages)

Note: I am using TexStudio 

So In reference section I can't see any text in it.

**Comment by fwalch** [comment]
Hey! It looks like you're using BibTeX, whereas the template uses an alternative called Biber. In TeXstudio, you can switch the bibliography tool in Options -> Configure TeXstudio -> Build -> Default Bibliography Tool.

If Biber is not available in your TeX Live version or something, you should be able to just change `backend=biber`  to `backend=bibtex` in `settings/packages.tex` to fix the problem.

**Comment by vinodrajendran001** [comment]
I changed it to **biber**, and now it's compiling without error, but in the place of citation it throws **??**

**Comment by fwalch** [comment]
Maybe try compiling again? LaTeX needs to make multiple passes over the document to resolve references and so on.. strange that TeXstudio doesn't take care of that, though.

**Comment by vinodrajendran001** [comment]
I tried changing compiler to **bibtex** and then added the line **backend=bibtex** in **settings/packages.tex**, now it works!
